# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20161205_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255)),
                ('description', models.CharField(help_text='What this URL pattern covers.', max_length=75)),
            ],
        ),
        migrations.RenameModel(
            old_name='UnderConstruction',
            new_name='Maintenance',
        ),
        migrations.AddField(
            model_name='ignoredurl',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Maintenance'),
        ),
    ]
