# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20161205_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='underconstruction',
            old_name='title',
            new_name='name',
        ),
    ]
