# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20161205_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='active',
            field=models.BooleanField(default=False, verbose_name='In Maintenance Mode'),
        ),
    ]
